### PR TITLE
fix(dex): correct history log page display issue

### LINKED ISSUE #46: Dex History Log Page
UI improvements needed, similar to the Activity Log page.

**Description:**
1. Scrollbar style is not aligned with the application’s design.
2. Horizontal scrolling is missing, preventing users from viewing timestamps.
3. Div-based layout should be replaced with tables for semantic design.

**Expected Behavior:**
- Style scrollbars to match the application’s design.
- Enable horizontal scrolling for timestamp visibility.
- Use tables instead of divs for a more semantic UI.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

### PR DESCRIPTION
**Pull request by Benjtalkshow**
## Description
- [x] Style scrollbars to match the application’s design.
- [x] Enable horizontal scrolling for timestamp visibility.
- [x] Use tables instead of divs for a more semantic UI.
## Extra
- [x] Moved constants data into `constants/history.ts`
## Proof
[Watch Video](https://www.webmobilefirst.com/en/screencasts/_77jb8yawncaad/)

## Related Issue(s)

Closes #46 
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves

Kindly Review @Abeeujah

### CODE REVIEW

**Comment by princeibs** [comment]
> Screenshot 2024-12-16 at 17 52 34 Fix irregularities in the footer and header images. It seems to repeat on desktop screens

@Benjtalkshow

**Comment by Benjtalkshow** [comment]
> > Screenshot 2024-12-16 at 17 52 34 Fix irregularities in the footer and header images. It seems to repeat on desktop screens
> 
> @Benjtalkshow

Alright

**Comment by Benjtalkshow** [comment]
> Table content should always be between the blue images at the top and bottom of the screen just like in the desktop version.

I have done this

**Comment by Benjtalkshow** [comment]
> Screenshot 2024-12-16 at 17 52 34 Fix irregularities in the footer and header images. It seems to repeat on desktop screens

But i dont understand this correction. Can you explain it more?

**Pull request merged**
