### PR TITLE
feat: fix help center page

### LINKED ISSUE #48: Help Center Page
Form and layout issues.

**Description:**
1. Attachments field uses the wrong input type.
2. No input validation for required fields.
3. Missing submit handler for the form.
4. Caret (Subject input field) lacks padding, causing it to appear cramped.

**Expected Behavior:**
- Use the correct input type for attachments.
- Implement input validation for required fields.
- Add a functional submit handler.
- Adjust caret padding using styles such as `border-r-8 border-bg`.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

### PR DESCRIPTION
**Pull request by No-bodyq**
## Description

_Detailed description of proposed changes_

## Related Issue(s)

Closes #48 
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Comment by No-bodyq** [comment]
Please review @Abeeujah, @Oshioke-Salaki

**Comment by No-bodyq** [comment]
Please review @Abeeujah, @Oshioke-Salaki

**Comment by Oshioke-Salaki** [comment]
Screenshot 2024-12-16 at 18 04 23
There is a lot of space between the left and right hand sides of this page.

Also the attachments input does not match the one on the [figma](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=749-810&t=bLKTfYuzPAmiToC7-0)

Also when a file is attached, it is supposed to show that a file has been inputted.

**Comment by No-bodyq** [comment]
Okay thank you, I will fix that

**Comment by No-bodyq** [comment]
Yes, I'll do that

**Comment by No-bodyq** [comment]
Made requested changes @Oshioke-Salaki, @princeibs

**Comment by No-bodyq** [comment]
Hello @Oshioke-Salaki, I don't think that is on my end:
The error is in select-base-token.tsx according to the workflow which i did not touch.
Please confirm

**Comment by Oshioke-Salaki** [comment]
Implement drag and drop functionality in the attachments

**Comment by No-bodyq** [comment]
Done @Oshioke-Salaki

**Comment by No-bodyq** [comment]
Any other corrections @Oshioke-Salaki  @princeibs

**Pull request merged**
