### PR TITLE
feat: implement dex swapper page

### LINKED ISSUE #8: Implement DEX swapper page
Implement a pixel perfect DEX swapper page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

### PR DESCRIPTION
**Pull request by zintarh**
## Description

_Detailed description of proposed changes_

Develop the DEX Swapper page by converting the Figma design into a functional implementation.

## Related Issue(s)

Closes #8 
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Comment by Oshioke-Salaki** [comment]
Your build is failing

**Review by princeibs — CHANGES_REQUESTED** [review]
image
@zintarh build should pass once you fix this

**Comment by zintarh** [comment]
@princeibs Please review, I've effected the changes

**Comment by Oshioke-Salaki** [comment]
Please make responsive on phones and tablets.

**Pull request merged**
