### PR TITLE
feat: add connect wallet functionality

### PR DESCRIPTION
**Pull request by Joy-Adah**
## Description

This PR implements the connect wallet window and its functionality.

### CODE REVIEW

**Comment by Joy-Adah** [comment]
hey @Oshioke-Salaki kindly review :)

**Comment by Joy-Adah** [comment]
hey @Oshioke-Salaki kindly review

**Comment by Joy-Adah** [comment]
hey @Oshioke-Salaki review :)

**Comment by Oshioke-Salaki** [comment]
LGTM 🚀

**Pull request merged**
