### PR TITLE
refactor: updated activity log page design

### LINKED ISSUE #45: Activity Log Page
UI improvements needed.

**Description:**
1. Footer cropping into page content due to lack of negative space.
2. Scrollbar style is not aligned with the application’s design.
3. Horizontal scrolling is missing, preventing users from viewing timestamps on smaller screens.
4. Div-based layout is less semantic; tables should be used instead for better accessibility.

**Expected Behavior:**
- Add sufficient negative space to prevent footer overlap.
- Style scrollbars to match the application’s design.
- Enable horizontal scrolling for timestamp visibility.
- Use tables instead of divs for a more semantic UI.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

### PR DESCRIPTION
**Pull request by abdegenius**
## Description
Made the neccessary adjustments as requested

## Related Issue(s)

Closes #45
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Comment by abdegenius** [comment]
@Abeeujah Please check PR and revert with any correction needed. Thanks!

**Comment by Oshioke-Salaki** [comment]
Screenshot 2024-12-16 at 17 36 00
The table should not overlap the blue picture. so the content will be readable

**Comment by Oshioke-Salaki** [comment]
The gap between table rows on mobile screens are a bit too much

**Comment by Oshioke-Salaki** [comment]
> Screenshot 2024-12-16 at 17 36 00 The table should not overlap the blue picture. so the content will be readable



It should be like this,
Screenshot 2024-12-16 at 17 47 48

**Review by princeibs — CHANGES_REQUESTED** [review]
Please check to verify that the footer does not overlap with the table

**Comment by abdegenius** [comment]
On it

**Comment by Oshioke-Salaki** [comment]
resolve conflicts

**Comment by abdegenius** [comment]
Please check the UI Design @Oshioke-Salaki fixed it

**Comment by Abeeujah** [comment]
Hi @abdegenius Please re-sync your fork.

**Pull request closed without merging**
