### PR TITLE
feat: implement autoswappr activity log

### LINKED ISSUE #7: Implement the Activity log page
Implement a pixel perfect activity log page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

### PR DESCRIPTION
**Pull request by anonfedora**
## Implement autoswappr activity log

_Detailed description of proposed changes_

## Related Issue(s)

Closes #7 
## Checklist:

- [x] Read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [x] Verified this is not a duplicate of any existing pull request

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)

### CODE REVIEW

**Comment by Oshioke-Salaki** [comment]
Gm, your build is failing. please fix it

**Comment by Oshioke-Salaki** [comment]
Any progress on this @anonfedora ? I need an update by the end of today

**Comment by anonfedora** [comment]
Hi ser @Oshioke-Salaki, seems there's no svg type in the public/coin-logos directory, should i import it from the figma?

**Comment by Oshioke-Salaki** [comment]
> Hi ser @Oshioke-Salaki, seems there's no svg type in the public/coin-logos directory, should i import it from the figma?

Yes you can replace the current icons in that directory with the `svg` versions from figma. But make sure you effect changes where the `png` versions where used previously.

**Comment by anonfedora** [comment]
Noted ser

**Pull request merged**
